branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '8'
before_install:
- yarn global add greenkeeper-lockfile@1
- sudo apt-get update -q -y
- sudo apt-get install -y realpath
before_script:
- greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
notifications:
  slack:
    secure: IgwEjeN5cfZMm+zOnxiL7Gd1F4JYL+CFlNoEO5NbQ9Nl+OPRF3DI33mumC7AvBx32i0xmd62MYdLs8hSKQfmrv/amq1mxEqpnvATNh58v9SOMzAw5zscf5TMgSD4L3jzAQ4kLkws1DCxq8TaaukErQYVIUU0n6ILJQ3UuUGPjKLX7R2CwjzPVNeCbBxyJ6c/kwmVOEn//E5be+Y3g044AfeJZ8Q99oVIKqzgxI+kkDwuc4bkbQwP+p6hDcXAuy13ewoTz/f6oAUjcgJUwKUAe0LiVVS46aXT1ftBUQN8wA/KEgC4TdMsfmOI4XbzW9g7xhngAZ5DdB+wJ2R2TGhpqSjZ7yCQGMH4yM/2QU4dMEQUd1A9H0bYCaC449yp+WVIDz78bC4GQA1UA8RzeM8EHb5GHRQu1LloHTVSdVoTjbngPMFv6lJj7AjhAfPgi7IyO2DIp2J7f2/2FdxRVIq+TRwBNQdo1/G+XvQFNtev5o5ANiIa/r+fmE5i1yi0ZVfpe3ojerrTxArtn6VRazO7SdiyW+injMSx+NlGj3qtJVGNrzQNlC9lpOMN/Y4Y3NWSnlNumRNAxBGEUS7hnRPBRrkovUe6mdLRI4oSkVl4cwR8XNh+R31IJl9g7XpehBmkXWh+gq44S82Y+dTvbvOCidgd55AQNVTOp0XE//hE5TQ=
